name: 'Install 1password cli tool'
description: ''

runs:
  using: "composite"
  steps:
    # Copy file
    - name: Copy zip file
      shell: bash
      run: |
        cp  ${{ github.action_path }}/op_linux_386_v2.16.1.zip .

    # Install 1pass cli
    - name: Install 1pass cli
      shell: bash
      run: |
        sudo unzip op_linux_386_v2.16.1.zip -d /usr/local/bin
        sudo rm op_linux_386_v2.16.1.zip
        sudo chmod +x /usr/local/bin/op
        op --version