name: Turn off downpage

on:
  workflow_dispatch:
    inputs:
      environement:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

jobs:
  downpage-off:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environement }}" >> $GITHUB_ENV
      - name: Login Openshift and turn off downpage
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}
          oc patch route bc-registry-search-prod -p '{"spec": {"to": {"name": "search-web-prod"}, "port": {"targetPort": "search-web-prod-tcp"}}}' -n ${{secrets.OPENSHIFT4_NAMESPACE_FRONTEND}}-prod
          oc patch route bc-registry-namerequest-prod -p '{"spec": {"to": {"name": "namerequest-prod"}, "port": {"targetPort": "namerequest-prod-tcp"}}}' -n ${{secrets.OPENSHIFT4_NAMESPACE_FRONTEND}}-prod
          oc patch route bc-registry-business-prod -p '{"spec": {"to": {"name": "business-filings-prod"}, "port": {"targetPort": "business-filings-prod-tcp"}}}' -n ${{secrets.OPENSHIFT4_NAMESPACE_FRONTEND}}-prod
          oc patch route bc-registry-auth-prod -p '{"spec": {"to": {"name": "auth-web-prod"}, "port": {"targetPort": "auth-web-prod-tcp"}}}' -n ${{secrets.OPENSHIFT4_NAMESPACE_FRONTEND}}-prod

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master

        with:
          type: ${{ job.status }}
          job_name: "*Downpage is OFF on ${{env.TAG_NAME}}*"
          channel: "#registries-ops"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: false
          token: ${{ secrets.GITHUB_TOKEN }}
